version: '3.8'

name: hackerrank_problems

services:
  sql_problems:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456root
      MYSQL_DATABASE: hackerrank
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - sql_problems_data:/var/lib/mysql
volumes:
  sql_problems_data: